# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Scruffypixels &mdash; the Portfolio of Mike Dwyer
email: mike@scruffypixels.com
description: > # this means to ignore newlines until "baseurl:"
  Mike Dwyer is a San Diego-based designer and front-end developer
  obsessed with clean designs, good code, and great chicken wings.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.scruffypixels.com" # the base hostname & protocol for your site
twitter_username: scruffypixels
github_username:  scruffypixels

# Build settings
markdown: kramdown

permalink: /:slug/

sass:
    style: compressed